[package]
name = "marketplace"
version = "1.0.0"
authors = [ "Rene Ďuriš",]
edition = "2021"
publish = false

[lib]
path = "src/marketplace.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.elrond-wasm]
version = "0.34.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.1"
