[package]
name = "marketplace-meta"
version = "1.0.0"
edition = "2021"
publish = false
authors = [ "René Ďuriš",]

[dev-dependencies]

[dependencies.marketplace]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
